### DISCUSSION TITLE
Upgrading from 2.4.2 to 2.4.7

### DISCUSSION THREAD

**Discussion by dynamicapps** [markshust/docker-magento#1197] [Q&A] [answered]
I have my 2.4.2 site from cloud commerce running in docker (thanks Mark!). I want to upgrade to 2.4.7 in a docker instance before I do it on my staging and then production servers.
My main question is which containers I should just get current images of vs. which I need to go through an upgrade process on.
I appreciate any suggestions.

**Comment by YevhenZvieriev** [comment, marked as answer]
Hello, @dynamicapps 

I have also upgraded my sandbox Magento instance from 2.4.2 to 2.4.7 so hope I will help you :)

## Containers to Simply Update:

### Nginx (app):

2.4.2: markoshust/magento-nginx:1.18-8

2.4.7: markoshust/magento-nginx:1.24-0

### PHP-FPM (phpfpm):

2.4.2: markoshust/magento-php:7.4-fpm

2.4.7: markoshust/magento-php:8.3-fpm-2

### Redis:

2.4.2: redis:6.0

2.4.7: redis:7.2-alpine

### Mailcatcher:

Image hasn't changed: sj26/mailcatcher

No update is needed.

### RabbitMQ:

2.4.2: rabbitmq:3.8

2.4.7: markoshust/magento-rabbitmq:3.12-0

## Containers Requiring Additional Steps:

### MariaDB (db):

2.4.2: mariadb:10.4

2.4.7: mariadb:10.6

Updating the database may require additional migration steps. It is recommended to back up your data before updating.

### Elasticsearch/OpenSearch:

2.4.2: markoshust/magento-elasticsearch:7.9

2.4.7: markoshust/magento-opensearch:2.12-0

After updating the image, you might need to update the Elasticsearch or OpenSearch indices.

In my case `compose.yaml` for 2.4.7 looks like:

``` 
services:
  app:
    image: markoshust/magento-nginx:1.24-0
    ports:
      - "80:8000"
      - "443:8443"
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    image: markoshust/magento-php:8.3-fpm-2
    volumes: *appvolumes
    env_file: env/phpfpm.env

  db:
    image: mariadb:10.6
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  opensearch:
    image: markoshust/magento-opensearch:2.12-0
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file: env/opensearch.env
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"

  rabbitmq:
    image: markoshust/magento-rabbitmq:3.12-0
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: env/rabbitmq.env

  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "1080:1080"
    
volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:
```
## My friendly recommendations:

1. Always create backups of important data, particularly databases, before updating.

2. Test the update on a staging environment before making changes in production.

3. Review the official Magento documentation and release notes to account for all possible changes and requirements for the new version.

BTW, feel free to use the script `bin/check-dependencies` that I developed, hope it will be useful for you during the upgrading process.

If you have any additional questions or need further assistance, feel free to reach out :)
