### DISCUSSION TITLE
PHP version for setup

### DISCUSSION THREAD

**Discussion by zukovasmartynas** [markshust/docker-magento#1216] [Q&A]
Hello, it is my first time using this repo

Im at setup step (creating simple magento project)
I have used oneliner setup command
https://github.com/markshust/docker-magento?tab=readme-ov-file#setup

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires magento/product-community-edition 2.4.6-p7 -> satisfiable by magento/product-community-edition[2.4.6-p7].
    - magento/product-community-edition 2.4.6-p7 requires php ~8.1.0||~8.2.0 -> your php version (8.3.6) does not satisfy that requirement.
`

Theo only thing that I have changed is to use different magento version 2.4.6-p7
But composer fails because it uses php 8.3. Is there a way to use different php version (in my case I need 8.1) ? 

Like to pass as parameter. I cant find this info in the readme.
Maybe I have missed a step or something

**Comment by its-leofisher** [comment]
This provides some insight: https://github.com/markshust/docker-magento/issues/1102

This is how my compose.yaml file looks:
```yaml
  phpfpm:
    image: markoshust/magento-php:8.2-fpm-4
    volumes: *appvolumes
    env_file: env/phpfpm.env
    #extra_hosts: *appextrahosts
```
