### DISCUSSION TITLE
How to change the timezone in the container??

### DISCUSSION THREAD

**Discussion by tomasperezponisio** [markshust/docker-magento#1249] [Q&A]
Hi there, my current timezone is 'UTC -3' (Time zone: America/Argentina/Buenos_Aires (-03, -0300)) , and if go inside the app container using bin/bash i see the timezone is 'UTC +000',  how can i change this? so the container has the same timezone as my computer? Thanks!

**Comment by YevhenZvieriev** [comment]
Hi, @tomasperezponisio 

You can set the TZ environment variable to specify the timezone.

Add the `TZ` environment variable in the `compose.yaml` file:

```
  phpfpm:
    image: markoshust/magento-php:8.3-fpm-2
    volumes: *appvolumes
    env_file: env/phpfpm.env
    environment:
      - TZ=America/Argentina/Buenos_Aires
    #extra_hosts: *appextrahosts

```

Restart the container using the `bin/restart` script to apply changes.

After applying any of these changes, you can verify the timezone inside the container using the `bin/cli date` script.

This should show the time in your desired timezone.
