### DISCUSSION TITLE
Where do I add the path of my existing project, which is located in src/magento?

### DISCUSSION THREAD

**Discussion by GNUXDAR** [markshust/docker-magento#1270] [General]
How do I redirect the path of the `src`, since the repository of a project I am downloading is in a `magento` directory? When I run `git clone path-repo src`, the directory ends up as `src/magento`, where the modules are located in `src/magento/app/code/[MODULES]`. I need help, please.

Inside src
![Coffret-Prestige-GiftJoy-CP-·-GitLab-12-10-2024_01_56_PM](https://github.com/user-attachments/assets/2b43b113-b5ac-4d7e-9af3-05104ac61d24)

**Steps To Reproduce**
1.     ✅ mhdir -p ~/home/gnuxdar/GNUXDAR/desweb/magento246
2.     ✅ cd _$
3.     ✅ curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
4.     ✅ git@gitlab.com:vendor/repo.git src
5.     ✅ bin/start --no-dev
6.     ✅ bin/copytocontainer --all
7.     ❌ bin/composer install

bin/composer install
Composer could not find a composer.json file in /var/www/html
To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage

**Comment by its-leofisher** [comment]
If your magento folder is it's own repo "submodule" then its just easier to move the code under src and move all the other files on the same level of your magento folder somewhere else.

If not, then one way to do it is to update default.conf to point to `/var/www/html/magento` which from the way I would do it is to copy default.conf from [`images/nginx` in Marks repo](https://github.com/markshust/docker-magento/tree/release/next/images/nginx), and 
Update `set $MAGE_ROOT /var/www/html/magento;` inside the 8443 server block just before the include.

Now mount the default.conf to the container by adding `- ./images/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf` to compose.yaml App volumes directive.  

This is not tested by the way, I had to set up sub-directories for multiple stores and this was the approach I took.   

```yaml
services:
  app:
    image: markoshust/magento-nginx:1.24-0
    ports:
      - "80:8000"
      - "443:8443"
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - ./images/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
```
