### DISCUSSION TITLE
Deploying to Staging or Production

### DISCUSSION THREAD

**Discussion by EmperorKonstantin** [markshust/docker-magento#395] [Ideas]
In an ideal world, we can rely on composer working and you can simply push your commits to your git repository and then your CI/CD pipeline will handle deployment from there. 

What sort of deployment setups do you guys use?

I used to push my commits to the repo, and then have webhooks setup in github or gitlab to trigger a php script on the server to do a
```php
<?php

// GitHub Webhook Secret.
// Keep it the same with the 'Secret' field on your Webhooks / Manage webhook page of your repository.
$secret = blaBlaSecreBla;

// Path to your respostory on your server.
// e.g. "/var/www/respostory"
$path = '/var/www/mymagentowebsite.com';

// Headers deliveried from GitHub
$signature = $_SERVER['HTTP_X_HUB_SIGNATURE'];

if ($signature) {
    $hash = "sha1=".hash_hmac('sha1', file_get_contents("php://input"), $secret);
    if (strcmp($signature, $hash) == 0) {
        echo shell_exec("cd {$path} && /usr/bin/git reset --hard origin/master && /usr/bin/git clean -f && /usr/bin/git pull origin master 2>&1");
        echo shell_exec("cd {$path} && composer install -y");
        echo shell_exce("curl -X POST 'https://api.cloudflare.com/client/v4/zones/blablasecretbla/purge_cache' -H 'Authorization: Bearer blaBlaSecreBla' -H 'Content-Type:application/json' --data '{\"purge_everything\":true}' --silent --output /dev/null");
            exit();
    }
}

http_response_code(404);
```

now with containers and Kubernetes everywhere I'm finding my deployment flow has to change... because setting up production environments is a far bigger pain than setting up a development environment. A performant Magento 2 deployment with a large amount of traffic can easily have more than 20-30 containers supporting it.

**Comment by EmperorKonstantin** [comment]
Here's an example bash script that generates / renews Let's Encrypt certs. 

You could generate them right into the env directory (this also does Clouflare DNS auth and generates a wildcard certificate):

```yaml
services:
  app:
    volumes: &appvolumes
      - ... (skip)
      - ./env/ssl/live/example.com/privkey.pem:/etc/nginx/certs/nginx.key:cached
      - ./env/ssl/live/example.com/fullchain.pem:/etc/nginx/certs/nginx.crt:cached
```


```bash
# Generate wildcard Let's Encrypt certificate if it does not exist
if test -f ~./teknova/env/ssl/live/teknova.com/fullchain.pem; then
certbot certonly --email emperorkonstantin@example.com --server https://acme-v02.api.letsencrypt.org/directory --agree-tos --dns-cloudflare --dns-cloudflare-credentials ~./docker-magento/env/certbot.env --dns-cloudflare-propagation-seconds 60 --config-dir ~./ssl/ --work-dir ~./docker-magento/env/ssl/ --logs-dir ~./docker-magento/env/ssl/ -d *.example.com -d example.com
fi

# Check if any certificates need to be renewed
certbot renew --email emperorkonstantin@example.com --server https://acme-v02.api.letsencrypt.org/directory --agree-tos --dns-cloudflare --dns-cloudflare-credentials ~./docker-magento/env/certbot.env --dns-cloudflare-propagation-seconds 60 --config-dir ~./ssl/ --work-dir ~./docker-magento/env/ssl/ --logs-dir ~./docker-magento/env/ssl/

# Restart docker image to apply the SSL updates
# echo "Restarting containers to apply updates..."
( cd /home/ubuntu/docker-magento && bin/restart )
```

I'm still not doing a large scale deployment due to no need.

**Reply by cooperRjp** [reply]
Are you running this docker setup in production or have you made your own with this as a base. My current site is just an ec2 instance with no containers and i'm looking to switch to something better e.g. docker and Kubernetes

**Reply by EmperorKonstantin** [reply]
I run this in production no problem. Though I've heavily modified it by now and am implementing a custom CI/CD pipeline. It's pretty secure as well.

I've had 2 downtimes that were automatically resolved in minutes in the past month. Here's a big hint:

```yml
services:
  app:
    image: markoshust/magento-nginx:1.18-4
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
    restart: on-failure
```

You really want that `restart: on-failure` there for every service. I also have some other mitigations that restart any locked up containers. Working on creating fail over as well as autoscaling, but Terraform will help me handle that.
