### DISCUSSION TITLE
About changing port assigned to db contianer

### DISCUSSION THREAD

**Discussion by dennismok2018** [markshust/docker-magento#645] [Q&A]
I tried assigning different port other than 3306 to mysql container by modifying docker-compose.yml 
like this:
```
    ports:
      - "3360:3306"
```
But it seems it doesn't do the trick as after bin/restart I got:
```
2 exception(s):
Exception #0 (Zend_Db_Adapter_Exception): SQLSTATE[HY000] [2002] Connection refused
Exception #1 (PDOException): SQLSTATE[HY000] [2002] Connection refused
```
when I load into https://magento.test/

What else should I change so that I can correctly change the port I assign to the db container?

**Comment by rangerz** [comment]
How did you assign the port ?

This way is work for me
```
db:
    ports:
      - "3360:13306"
```

**Reply by dennismok2018** [reply]
```
  db:
    image: mariadb:10.4
    command: --max_allowed_packet=64M
    ports:
      - "3360:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql
    extra_hosts: *appextrahosts
```
Basically same as yours. Since your example used 13306 port in the container, I also tried changing mine to 13306, 
same exceptions. I tried using MysqlWorkbench to connect the db through 3360 and it connected. 

I'm on MacOs Big Sur 11.6 and I also have a local mysql installed with 3306 as default port. (But I turned this local one off whenever I use the containers) Don't know if these details are affecting.
