### DISCUSSION TITLE
PhpStorm: Incoming Connection From Xdebug

### DISCUSSION THREAD

**Discussion by overrode** [markshust/docker-magento#647] [Q&A]
Im using PhpStorm on Linux and  everytime i refresh the page, i get a pop-up with the message "Incoming Connection From Xdebug" which has different port and no Server name:
![xdebug_incoming](https://user-images.githubusercontent.com/15195423/155284021-33e7d522-7154-4925-9b9f-6e7eb313b706.png)

And it also creates an EMPTY Server name:
![xdebug_incoming_empty](https://user-images.githubusercontent.com/15195423/155284023-81cdafba-b197-465d-ae6d-7e5618787f48.png)

I have my custom-server test.local with the port 80 and the path mapping setting and it works only if i click Run -> Debug 'test.local' and wait for the page refresh.

So, for some reason, the Xdebug does not take my custom-server name (test.local, which works) and allways creates an empty one.
If i click Accept it gives me an error:
![xdebug_incoming_error](https://user-images.githubusercontent.com/15195423/155284538-ee45303e-60fa-4d6a-96b1-60b366dc60ab.png)

Any ideea how to get the Xdebug to use my custon Server name (test.local) when i enable the Listener and refresh the page?

**Comment by kevinjavitz** [comment]
I have the same issue, have you found any solution?

**Comment by asannikov** [comment]
same for me...just modify your compose.yaml file:

```
  phpfpm:
    image: markoshust/magento-php:7.4-fpm-15
    volumes: *appvolumes
    env_file: env/phpfpm.env
    #extra_hosts: *appextrahosts
    environment:
      PHP_IDE_CONFIG: "serverName=magento.test"
```
PHP_IDE_CONFIG: "serverName=magento.test" is added here
