### DISCUSSION TITLE
Add MongoDB to the setup

### DISCUSSION THREAD

**Discussion by malikabid** [markshust/docker-magento#681] [Ideas]
HI @markshust 

I am using this docker setup for all my projects on local machine. So far working great and the whole team has finally adapted it. Thank you. 
But, I have a unique requirement for one of my client project, along the mariadb, there is some data coming from a mongo db.
Can you please help setting it up in your docker.ymls.

**Comment by malikabid** [comment]
Hi Finally I was able to add mongodb to my setup by adding the following lines into my docker-compose.yml file

```
mongodb:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongodb_dir:/data/db
    ports:
      - '27017-27019:27017-27019'
    extra_hosts: *appextrahosts
```
Now I need to edit the php-fpm image to include the php-mongodb extension - Any help would be appreciated here.  @markshust
