### DISCUSSION TITLE
How do we import Cloudflare Certification to ower existing Magento

### DISCUSSION THREAD

**Discussion by ebaturan** [markshust/docker-magento#738] [General]
Is there a way how to imort the coudflare certification to our nginx in command line.. , I have try to other way di dnot work for me..
If there is a solution kindly share it with us.

I just create a certification on coudflare and try to import it to the magento existing source

By creating the files and importin the certication and private to the file and import them as on the fallowing command line
have not work for me.. 
# Copy the key and cert file over to your container

docker cp "./nginx.crt" "$(docker-compose ps -q app|awk '{print $1}')":/var/www/html
docker cp "./nginx.key" "$(docker-compose ps -q app|awk '{print $1}')":/var/www/html

# Set ownership and move them to the proper place in your container

docker-compose exec -T -u root app chown app:app nginx.key nginx.crt
docker-compose exec -T -u root app mv nginx.key nginx.crt /etc/nginx/certs/

# Restart your Magento environment

bin/stop
bin/start

**Comment by rangerz** [comment]
You don't need to copy cert file into contioner. Use mount will be more flexible.

Edit **docker-compose.dev.yml**
```
services:
  app:
    volumes: &appvolumes
      - ./env/nginx.key:/etc/nginx/certs/nginx.key:cached
      - ./env/nginx.crt:/etc/nginx/certs/nginx.crt:cached
```

And run `bin/restart`. Good Luck
