### ISSUE TITLE
Import large database - MySQL server has gone away 

### ISSUE THREAD

**Issue by alkrenawizid** [markshust/docker-magento#1055]
**Description**
**Hi @markshust** 
**I'm trying to import large database locally and get the below error message.**

`bin/mysql < db.sql`
**ERROR 2006 (HY000) at line 6292: MySQL server has gone away**

`bin/clinotty mysql -hdb -uroot -pmagento magento < db.sql`
**ERROR 2006 (HY000) at line 6292: MySQL server has gone away**

SED command that I used to remove DEFINER clauses:

>`sed -i '' 's/DEFINER=`[^`][^`]*`@`[^`][^`]*`//g' db.sql`

**Steps To Reproduce**

- Try to import a large database (~ 18GB)

**Expected Result**
Database Imported successfully 

**Actual Result**
 MySQL server has gone away

**Comment by YevhenZvieriev** [comment]
Hi, @alkrenawizid 

Wow, you have a huge dump :)

I got your issue, you should increase the MySQL buffer pool size 


There are two ways to resolve this issue:

**First one**

You can do this in ```compose.yaml```  or ```my.cnf``` file

Follow next steps:

1. Open ```compose.yaml```, and add ```./images/mysql/conf/my.cnf:/etc/mysql/conf.d/custom.cnf:cached``` into db service -> volumes.

So, your ```compose.yaml``` should look like this:

```
 db:
    image: mariadb:10.6
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql  
      - ./images/mysql/conf/my.cnf:/etc/mysql/conf.d/custom.cnf:cached
 ```

2. ```mkdir -p images/mysql/conf```

3.  ```vi images/mysql/conf/my.cnf```

And paste follow into ```my.cnf```:

```
[mysqld]
innodb_buffer_pool_size=256M
```

4. and execute ```bin/restart db``` service.

5. Try to import a database again.


**Second one**

***You can also do easier:***

1. Open ```compose.yaml```, and add ```--innodb_buffer_pool_size=256M``` into db service -> command.

So, your ```compose.yaml``` should look like this:

```
  db:
    image: mariadb:10.6
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
      --innodb_buffer_pool_size=256M
 ```


After executing  ```bin/restart db``` try to import a database again.

So that`s a very easy way to do this.

To check you should execute:

```
bin/mysql
```

And execute ```SHOW VARIABLES LIKE 'innodb_buffer_pool_size';```

And pay attention to the Value! It should seem 268435456

I hope it will help you!
