### ISSUE TITLE
Unable to Start ES v8.11

### ISSUE THREAD

**Issue by joesken** [markshust/docker-magento#1159]
Is anyone else having an issue getting ESv8.11 to start up correctly?

Very early in the setup process when it is initialising the containers with `bin/start` the ES container will not start up. It tries to start up and then quits after ~150 seconds with `container for service "elasticsearch" is unhealthy`.

Looking at the docker logs I can see the following entries with a repeated WARN message then which I guess must be the fundamental issue here however I'm not clear on how to rectify it.

```
{"@timestamp":"2024-05-17T14:54:59.036Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.23.0.2:9200, remoteAddress=/172.23.0.2:54962}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[7be26ee5ecbc][transport_worker][T#3]","log.logger":"org.elasticsearch.http.netty4.Netty4HttpServerTransport","elasticsearch.cluster.uuid":"iYQeyZGJSieJTzd7CWj4TA","elasticsearch.node.id":"W1661PUQQDe8sbrh9c06fQ","elasticsearch.node.name":"7be26ee5ecbc","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2024-05-17T14:55:04.082Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.23.0.2:9200, remoteAddress=/172.23.0.2:54968}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[7be26ee5ecbc][transport_worker][T#4]","log.logger":"org.elasticsearch.http.netty4.Netty4HttpServerTransport","elasticsearch.cluster.uuid":"iYQeyZGJSieJTzd7CWj4TA","elasticsearch.node.id":"W1661PUQQDe8sbrh9c06fQ","elasticsearch.node.name":"7be26ee5ecbc","elasticsearch.cluster.name":"docker-cluster"}

```

Have the following in compose.yaml

```
  elasticsearch:
    image: markoshust/magento-elasticsearch:8.11
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file: env/elasticsearch.env
    environment:
      - "discovery.type=single-node"
  #    ## Avoid test failures due to small disks
  #    ## More info at https://github.com/markshust/docker-magento/issues/488
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
  #    ## Uncomment to set custom heap size to avoid memory errors
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
  #    ## Uncomment to increase the virtual memory map count
      - "max_map_count=262144"

```
* tried commenting / uncommenting various options but no luck. Also tried removing docker images and pulling again but similarly no luck.

Running Magento 2.4.7 (although it isn't getting that far in the process really that it is an issue).
Running Ubuntu 20.04

Any pointers or similar occurences appreciated. There was a vague reference to the same error in this issue https://github.com/markshust/docker-magento/issues/1133 but no real relevant detail for me on a solution. Thanks.

Joseph
