### ISSUE TITLE
Magento 2.4.4-p8 Call to undefined method ReflectionUnionType::getName()

### ISSUE THREAD

**Issue by anthonyvallone-paydock** [markshust/docker-magento#1160]
**Description**
When trying to build a 2.4.4-p8 container i get reflection errors and the container wont start.

**Steps To Reproduce**
1.  Create fresh container using the following files

Note: i have tried with both opensearch / elasticsearch and get the same issue.

docker-compose.yaml
```
services:
  app:
    image: markoshust/magento-nginx:1.24-0
    ports:
      - "80:8000"
      - "443:8443"
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    image: markoshust/magento-php:8.1-fpm
    volumes: *appvolumes
    env_file: env/phpfpm.env

  db:
    image: mariadb:10.4
    command: --max_allowed_packet=64M --optimizer_use_condition_selectivity=1 --optimizer_switch="rowid_filter=off"
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  opensearch:
    image: markoshust/magento-opensearch:1.2
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file: env/opensearch.env
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
    

  rabbitmq:
    image: markoshust/magento-rabbitmq:3.9
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: env/rabbitmq.env

  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "1080:1080"

volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:

```

**Expected Result**
The container to work.

**Actual Result**
The error

```
Call to undefined method ReflectionUnionType::getName()#0 /var/www/html/vendor/magento/framework/Code/Generator/EntityAbstract.php(393): Magento\Framework\Code\Generator\EntityAbstract->extractParameterType(Object(ReflectionParameter))
#1 /var/www/html/vendor/magento/framework/ObjectManager/Code/Generator/Proxy.php(176): Magento\Framework\Code\Generator\EntityAbstract->_getMethodParameterInfo(Object(ReflectionParameter))
#2 /var/www/html/vendor/magento/framework/ObjectManager/Code/Generator/Proxy.php(136): Magento\Framework\ObjectManager\Code\Generator\Proxy->_getMethodInfo(Object(ReflectionMethod))
#3 /var/www/html/vendor/magento/framework/Code/Generator/EntityAbstract.php(226): Magento\Framework\ObjectManager\Code\Generator\Proxy->_getClassMethods()
#4 /var/www/html/vendor/magento/framework/ObjectManager/Code/Generator/Proxy.php(160): Magento\Framework\Code\Generator\EntityAbstract->_generateCode()
#5 /var/www/html/vendor/magento/framework/Code/Generator/EntityAbstract.php(106): Magento\Framework\ObjectManager\Code\Generator\Proxy->_generateCode()
#6 /var/www/html/vendor/magento/framework/Code/Generator.php(130): Magento\Framework\Code\Generator\EntityAbstract->generate()
#7 /var/www/html/vendor/magento/framework/Code/Generator/Autoloader.php(53): Magento\Framework\Code\Generator->generateClass('Psr\\Log\\LoggerI...')
#8 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Psr\\Log\\LoggerI...')
#9 /var/www/html/vendor/magento/framework/ObjectManager/Relations/Runtime.php(38): class_exists('Psr\\Log\\LoggerI...')
#10 /var/www/html/vendor/magento/framework/Interception/Config/Config.php(157): Magento\Framework\ObjectManager\Relations\Runtime->has('Psr\\Log\\LoggerI...')
#11 /var/www/html/vendor/magento/framework/Interception/Config/Config.php(180): Magento\Framework\Interception\Config\Config->_inheritInterception('Psr\\Log\\LoggerI...')
#12 /var/www/html/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php(61): Magento\Framework\Interception\Config\Config->hasPlugins('Psr\\Log\\LoggerI...')
#13 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(47): Magento\Framework\Interception\ObjectManager\Config\Developer->getInstanceType('Psr\\Log\\LoggerI...')
#14 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Psr\\Log\\LoggerI...')
#15 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Psr\\Log\\LoggerI...')
#16 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Psr\\Log\\LoggerI...', NULL, 'logger', 'Magento\\Framewo...')
#17 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\Framewo...', Array, Array)
#18 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#19 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#20 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#21 /var/www/html/vendor/magento/framework/Interception/PluginList/PluginList.php(136): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#22 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\Interception\PluginList\PluginList->__construct(Object(Magento\Framework\ObjectManager\Config\Reader\Dom\Proxy), Object(Magento\Framework\Config\Scope), Object(Magento\Framework\App\Cache\Type\Config), Object(Magento\Framework\ObjectManager\Relations\Runtime), Object(Magento\Framework\Interception\ObjectManager\Config\Developer), Object(Magento\Framework\Interception\Definition\Runtime), Object(Magento\Framework\App\ObjectManager), Object(Magento\Framework\ObjectManager\Definition\Runtime), Array, 'plugin-list', NULL, NULL, NULL)
#23 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#24 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#25 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(42): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#26 /var/www/html/generated/code/Magento/Framework/App/MaintenanceMode/Interceptor.php(13): Magento\Framework\App\MaintenanceMode\Interceptor->___init()
#27 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\App\MaintenanceMode\Interceptor->__construct(Object(Magento\RemoteStorage\Filesystem), NULL)
#28 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#29 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#30 /var/www/html/setup/src/Magento/Setup/Di/MagentoDiFactory.php(24): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#31 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(620): Magento\Setup\Di\MagentoDiFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'Magento\\Framewo...', NULL)
#32 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(242): Laminas\ServiceManager\ServiceManager->doCreate('Magento\\Framewo...')
#33 /var/www/html/vendor/laminas/laminas-di/src/Resolver/TypeInjection.php(44): Laminas\ServiceManager\ServiceManager->get('Magento\\Framewo...')
#34 /var/www/html/vendor/laminas/laminas-di/src/Injector.php(202): Laminas\Di\Resolver\TypeInjection->toValue(Object(Laminas\ServiceManager\ServiceManager))
#35 /var/www/html/vendor/laminas/laminas-di/src/Injector.php(227): Laminas\Di\Injector->getInjectionValue(Object(Laminas\Di\Resolver\TypeInjection))
#36 /var/www/html/vendor/laminas/laminas-di/src/Injector.php(173): Laminas\Di\Injector->resolveParameters('Magento\\Setup\\C...', Array)
#37 /var/www/html/vendor/laminas/laminas-di/src/Injector.php(133): Laminas\Di\Injector->createInstance('Magento\\Setup\\C...', Array)
#38 /var/www/html/vendor/laminas/laminas-di/src/Container/AutowireFactory.php(61): Laminas\Di\Injector->create('Magento\\Setup\\C...', Array)
#39 /var/www/html/vendor/laminas/laminas-di/src/Container/ServiceManager/AutowireFactory.php(45): Laminas\Di\Container\AutowireFactory->create(Object(Laminas\ServiceManager\ServiceManager), 'Magento\\Setup\\C...', NULL)
#40 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(620): Laminas\Di\Container\ServiceManager\AutowireFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'Magento\\Setup\\C...', NULL)
#41 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(242): Laminas\ServiceManager\ServiceManager->doCreate('Magento\\Setup\\C...')
#42 /var/www/html/setup/src/Magento/Setup/Console/CommandList.php(88): Laminas\ServiceManager\ServiceManager->get('Magento\\Setup\\C...')
#43 /var/www/html/vendor/magento/framework/Console/Cli.php(148): Magento\Setup\Console\CommandList->getCommands()
#44 /var/www/html/vendor/magento/framework/Console/Cli.php(134): Magento\Framework\Console\Cli->getApplicationCommands()
#45 /var/www/html/vendor/symfony/console/Application.php(1286): Magento\Framework\Console\Cli->getDefaultCommands()
#46 /var/www/html/vendor/symfony/console/Application.php(631): Symfony\Component\Console\Application->init()
#47 /var/www/html/vendor/symfony/console/Application.php(237): Symfony\Component\Console\Application->find('module:disable')
#48 /var/www/html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 /var/www/html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#50 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#51 {main}
```
