### ISSUE TITLE
ER_CERT_AUTHORITY_INVALID when running MFTF tests

### ISSUE THREAD

**Issue by c-mc-cabe** [markshust/docker-magento#1169]
Up until this week my mftf work fine but now i get an error when running MFTF tests. Accessing the same host name from my mobile device and non container browser works ok, just when i use chrome driver it throws this issue?

I rebuilt my stack after updating to the latest version using bin/update, the only thing is i have switched the image to use a seleniarm image for the m2 chip on my mac

![image](https://github.com/markshust/docker-magento/assets/150677080/b4b8630e-a2d4-4332-b630-afdb382dc7cd)

**Comment by cmccabeesw** [comment]
A workaround is to add the cert into the selenium container:

Update your docker compose.yaml

```
  selenium:
    image: selenium/standalone-chromium:nightly
    ports:
      - "5900:5900"
      - "4444:4444"
      - "7900:7900"
    shm_size: 2g
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - DISPLAY=:99.0
    volumes:
      - ssldata:/etc/nginx/certs  # Mount the ssldata volume
 ``` 

Then run the command to add the cert on the selenium instance 


`docker exec -u root selenium_container_name /bin/bash -c "apt-get update && apt-get install -y libnss3-tools && certutil -d sql:/home/seluser/.pki/nssdb -A -t 'CP,CP,' -n MyCert -i /etc/nginx/certs/nginx.crt"`
