### ISSUE TITLE
During setting-up magento, facing issues with opensearch running.

### ISSUE THREAD

**Issue by tahercimp** [markshust/docker-magento#1279]
**Description**
When Im done creating the Setup & m2 dir, and running the curl command inside the m2 dir, everything is installed perfectly, but after that when the time comes for it to run & execute, only the opensearch gives error.
And due to this, I am unable to open m2.test on localhost.
This is the curl command that I had executed : 
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- m2.test 2.4.6 community

**Expected Result**
I got the below image from the youtube video by mark shust
![Image](https://github.com/user-attachments/assets/3b964f2c-1008-4670-988f-cb23548a7e46)

**Actual Result**
![Image](https://github.com/user-attachments/assets/11893893-8039-4cfa-98b8-394ac3af6efa)

**Comment by tahercimp** [comment]
I meant /Sites directory, not Setup, in the description.
My bad.

**Comment by tahercimp** [comment]
I tried to manually install docker-magento, changed the compose.yaml, compose.healthcheck.yaml, and bin/setup-install for elasticsearch instead of opensearch.
Then downloaded magento, everything was installed as expected, but then this time elasticsearch gave error : 

![Image](https://github.com/user-attachments/assets/3d0bf38b-1650-41bd-a81c-896febe8fd4d)

And when I checked elasticsearch's container, this was the error that it gave : 

![Image](https://github.com/user-attachments/assets/5a0ba8f4-97cf-479d-9881-f5fad1fe4e52)

And I am trying to get this done since two days, someone please help.

**Comment by krish512** [comment]
Replace the opensearch section in compose.yaml with elasticsearch container,

```
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: magento-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    ports:
      - "9200:9200"
```
