### ISSUE TITLE
Customizing the cron

### ISSUE THREAD

**Issue by sean-baran** [markshust/docker-magento#130]
Is there a straightforward way to override the default cron that is created in the image?

**Comment by markshust** [comment]
what are you trying to do?

**Comment by sean-baran** [comment]
We have file transfer tasks that do not work well when run from the Magento "cron". I created cron jobs for these tasks. So, I have a cron shell script that I must rerun every time I rebuild the container.

**Comment by markshust** [comment]
did you try host bind mounting to /etc/crontab?

if that doesn't work (possibly not because of ownership issues), i'd probably advise to use the `markoshust/magento-php:7.2-fpm-0` image as a base image, and build your own custom image from that, adding in your custom stuff like so:

Dockerfile:

```
FROM markoshust/magento-php:7.2-fpm-0
RUN printf '* *\t* * *\tapp\t%s/usr/local/bin/php /var/www/html/update/cron.php\n' >> /etc/crontab
```

then:

```
docker build -t myphpimage .
```

replacing the contents of the `/usr/local/bin/php /var/www/html/update/cron.php` line above with the script you wish to run. you can then use the `myphpimage` across your fleet of docker containers as your base image and update all references to point to that image.

**Comment by markshust** [comment]
just thought of one other possible method which may work. given this cron:

```
  cron:
    image: markoshust/magento-php:7.2-fpm-0
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    links:
      - db
    volumes: *appvolumes
```

you can append your oneliner to the command. it's kind of a workaround to avoid maintaining/building your own images. not sure if it'll work but it's worth a short. lmk and perhaps i can document this somewhere.

```
  cron:
    image: markoshust/magento-php:7.2-fpm-0
    user: root
    command: printf '* *\t* * *\tapp\t%s/usr/local/bin/php /var/www/html/update/cron.php\n' >> /etc/crontab && /usr/local/bin/cronstart
    tty: true
    links:
      - db
    volumes: *appvolumes
```
