### ISSUE TITLE
How to deploy to production (ssl certificate)?

### ISSUE THREAD

**Issue by plamenh** [markshust/docker-magento#440]
**Description**

Can't find instruction on how to deploy to production

**Steps To Reproduce**
1. Deploy to production
2. Get invalid certificate

**Expected Result**

Have a valid certificate

**Actual Result**

Certificate is invalid

Let's say we use LetsEcnrypt. Am I right thinking I need to put an Nginx proxy in front and change the listen port on the docker instance from 80/443 to something else, e.g. 8080 and 8443? Then use lets encrypt to get the certificate?

Or would you recommend somehow copying the obtained certs (no idea how we will obtain them automatically w/out Nginx or apache2, though) into the container at a set interval?

**Comment by rangerz** [comment]
Put `nginx.key` and `nginx.crt` in somewhere and link them by `docker-compose.dev.yml` setting

For example
```
services:
  app:
    volumes: &appvolumes
      - ... (skip)
      - ./env/nginx.key:/etc/nginx/certs/nginx.key:cached
      - ./env/nginx.crt:/etc/nginx/certs/nginx.crt:cached
```

Good Luck.

**Comment by EmperorKonstantin** [comment]
@rangerz Great idea! I just pared down my deploy bash script that generated / renewed Let's Encrypt certs. 

You could generate them right into the env directory (this also does DNS auth and generates a wildcard certificate):

```bash
certbot certonly --email emperorkonstantin@example.com --server https://acme-v02.api.letsencrypt.org/directory --agree-tos --dns-cloudflare --dns-cloudflare-credentials ~./docker-magento/env/certbot.env --dns-cloudflare-propagation-seconds 60 --config-dir ~./ssl/ --work-dir ~./docker-magento/env/ssl/ --logs-dir ~./docker-magento/env/ssl/ -d *.example.com -d example.com
```

```yaml
services:
  app:
    volumes: &appvolumes
      - ... (skip)
      - ./env/ssl/live/example.com/privkey.pem:/etc/nginx/certs/nginx.key:cached
      - ./env/ssl/live/example.com/fullchain.pem:/etc/nginx/certs/nginx.crt:cached
```
