### ISSUE TITLE
Kibana does not find elasticsearch

### ISSUE THREAD

**Issue by kamorana** [markshust/docker-magento#453]
I try to add kibana to the cluster.  So I've added kibana to the `docker-compose.yml` like that:

```
 kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
```

After `bin/restart` I only get:
`Kibana server is not ready yet`

The logs point out, that the Elasticsearch server could not be found. Although I can ping it with `ping elasticsearch`. I also tried to add a network to Kibana like:
`docker network ls` gave me this output:

```
NETWORK ID     NAME                  DRIVER    SCOPE
a230c9dac898   bridge                bridge    local
be08531a0582   host                  host      local
8db21f8376b0   magento-dev_default   bridge    local
8a9ceb436782   none                  null      local
```

So I used the `magento-dev_default` 

networks:
    - magento-dev_default

But this network is not recognized.

I would really appreciate your help.

**Comment by kamorana** [comment]
I got it running using no network (using default settings) but using a different Elasticsearch image which was compatible. It seems that the versions of Kibana and Elasticsearch were not compatible.

**I am using now:**

```
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
```
