### ISSUE TITLE
Nginx to phpfpm connection refused

### ISSUE THREAD

**Issue by hershkoy** [markshust/docker-magento#476]
I followed instructions for "Manual Setup=>Existing projects", but website doesn't load in the browser.

It seems there is no connection between nginx and phpfpm. I think that there is something missing in the docker-compose file

This is from within nginx container to the phpfpm:
```
~/html $ curl -vvv http://phpfpm:9001/health_check.php
*   Trying 172.19.0.7:9001...
* TCP_NODELAY set
* connect to 172.19.0.7 port 9001 failed: Connection refused
* Failed to connect to phpfpm port 9001: Connection refused
* Closing connection 0
curl: (7) Failed to connect to phpfpm port 9001: Connection refused
```
But there is ping:
```
/var/www/html # ping phpfpm
PING phpfpm (172.19.0.7): 56 data bytes
64 bytes from 172.19.0.7: seq=0 ttl=64 time=0.128 m
```

Containers:
```
ubuntu@DESKTOP-HED9HVG:/mnt/c/Users$ docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS                                                                                        NAMES
8db110d5737a        markoshust/magento-nginx:1.18-4            "/docker-entrypoint.…"   2 hours ago         Up 2 hours          80/tcp, 0.0.0.0:80->8000/tcp, 0.0.0.0:443->8443/tcp                                          localdev_app_1
74ff9e11646a        markoshust/magento-php:7.4-fpm-5           "docker-php-entrypoi…"   2 hours ago         Up 2 hours          9000-9001/tcp                                                                                localdev_phpfpm_1
```

php-fpm is working:

```
app@74ff9e11646a:~/html$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
app          1  0.0  0.2 222828 33168 ?        Ss   06:57   0:00 php-fpm: master process (/usr/local/etc/php-fpm.conf)
app          6  0.0  0.0 222828 10412 ?        S    06:57   0:00 php-fpm: pool www
app          7  0.0  0.0 222828 10348 ?        S    06:57   0:00 php-fpm: pool www
app          8  0.0  0.0 222828 10348 ?        S    06:57   0:00 php-fpm: pool www
app          9  0.0  0.0 222828 10348 ?        S    06:57   0:00 php-fpm: pool www
```
From what [I read here](https://stackoverflow.com/questions/47056062/how-to-connect-nginx-to-php-fpm-using-unix-socket-in-docker), it seems to me that maybe something with the socket is missing in the docker-compose file (phpfpm is not connected to anything?):

<details>
<summary>my current docker-compose.yml:</summary>

```
# Mark Shust's Docker Configuration for Magento
# (https://github.com/markshust/docker-magento)
#
# Version 37.0.2

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.18-4
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    image: markoshust/magento-php:7.4-fpm-5
    env_file: env/app.env
    links:
      - db
    volumes: *appvolumes

  db:
    image: percona:5.7
    command: --max_allowed_packet=64M
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:5.0-alpine

  elasticsearch:
    image: markoshust/magento-elasticsearch:7.7.1-0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:7.4-fpm-5
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:

```
</details>

I am windows10 wsl2. Any idea what I should check?
