### ISSUE TITLE
bin/download does not work with M1

### ISSUE THREAD

**Issue by chrene** [markshust/docker-magento#499]
Just wanted to let you know that I get the following error when using the `bin/download` command

```
Pulling db (percona:5.7)...
5.7: Pulling from library/percona
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

The solution I have used is to add `platform: linux/x86_64` in `docker-compose.yml`

```
services:
  db:
    platform: linux/x86_64
    image: percona:5.7
    ...
```

https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8
