### ISSUE TITLE
Add port 35729 to php container for work Live Reload with Grunt

### ISSUE THREAD

**Issue by artmouse** [markshust/docker-magento#635]
```
phpfpm:
    image: markoshust/magento-php:7.4-fpm-12
    ports:
      - "35729:35729"
    volumes: *appvolumes
    extra_hosts: *appextrahosts
    env_file: env/phpfpm.env
```
