### ISSUE TITLE
Fix possible slow reindexing on MariaDB

### ISSUE THREAD

**Issue by artmouse** [markshust/docker-magento#705]
Reindexing on MariaDB 10.4 takes more time compared to other MariaDB or MySQL versions. 
As a workaround, we suggest modifying the default MariaDB configuration and setting the following parameters:

optimizer_switch='rowid_filter=off'
optimizer_use_condition_selectivity = 1

With this properties catalog product reindex finish after 7 sec, without 5 min

![изображение](https://user-images.githubusercontent.com/527232/168483975-2a23ab0d-94de-4760-bf67-688941850f5a.png)

https://devdocs.magento.com/cloud/project/services-mysql.html

https://experienceleague.adobe.com/docs/commerce-operations/performance-best-practices/configuration.html

```
  db:
    image: mariadb:10.4
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql
    extra_hosts: *appextrahosts
```
