### ISSUE TITLE
Mounted php.ini breaks bin/xdebug enable

### ISSUE THREAD

**Issue by btantlinger** [markshust/docker-magento#803]
**Description**

I've mounted a modified php.ini  within docker-compose.dev.yml as described here https://courses.m.academy/courses/487758/lectures/36702861  E.g:

````
version: "3"
services:
  app:
    volumes: &appvolumes
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:cached
      - ./src:/var/www/html:cached
      - ./images/php/conf/php.ini:/usr/local/etc/php/php.ini:cached

  phpfpm:
    volumes: *appvolumes
````

This works and the php.ini changes are reflected within the container.  However, running `bin/xdebug` enable or `bin/xdebug disable` now fails  with the error message:

````
sed: cannot rename /usr/local/etc/php/sed6yUH4G: Device or resource busy
````
This is occuring on:
Manjaro Linux (arch based)
Docker version 20.10.18, build b40c2f6b5d
Docker Compose version 2.11.2

**Steps To Reproduce**

1. Mount php.ini from the host as described here https://courses.m.academy/courses/487758/lectures/36702861 
2. run bin/xdebug enable to enable xdebug

**Expected Result**

xdebug is enabled

**Actual Result**

Enabling xdebug fails with the message 

sed: cannot rename /usr/local/etc/php/sed6yUH4G: Device or resource busy
