### ISSUE TITLE
How to remove mkcert SSL(mkcert development certificate), install Let's Encrypt SSL Certificate

### ISSUE THREAD

**Issue by AngeloZou** [markshust/docker-magento#942]
**Description**
I installed magento 2.4.6 on vps (ubuntu 22.04).
I installed SSL (mkcert development certificate) through the official tutorial, but the website cannot use ssl normally. How can I remove mkcert development certificate and install Let's Encrypt SSL Certificate.

**Steps To Reproduce**
1. bin/setup-ssl
2. bin/setup-ssl-ca

**Expected Result**
The frontend SSL is valid
or
Install Let's Encrypt SSL Certificate.

**Actual Result**
The frontend SSL is invalid
Not secure https:/ /www.123456.com
Your connection to this site is not secure
Certificate is not valid
Chrome error page detail:
![Screenshot_2](https://github.com/markshust/docker-magento/assets/81738253/d36e0f25-0535-42ec-82af-9d3443969244)
![Screenshot_3](https://github.com/markshust/docker-magento/assets/81738253/05300de2-63c4-4ee6-b35e-dcbbca802ad6)

**Comment by rangerz** [comment]
1. Move your custom cert files (`nginx.crt` and `nginx.key`) to `env` folder

2. Edit `compose.dev.yaml`
```
services:
  app:
    volumes: &appvolumes
      - ./env/nginx.key:/etc/nginx/certs/nginx.key:cached
      - ./env/nginx.crt:/etc/nginx/certs/nginx.crt:cached
```

3. `bin/restart`
