### ISSUE TITLE
I am getting error after ran of "curl -s..." line on windows

### ISSUE THREAD

**Issue by BBartt** [markshust/docker-magento#972]
**Description**
I ran "curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.6 community" command

**Steps To Reproduce**
Run line: "curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.6 community"
I am using windows CMD

**Expected Result**

**Actual Result**
Error:
`Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:80 -> 0.0.0.0:0: listen tcp 0.0.0.0:80: bind: permission denied`

**Comment by artmouse** [comment]
Do you use WSL?

**Comment by memory-hunter** [comment]
```bash
sudo sysctl net.ipv4.ip_unprivileged_port_start=0
bin/removall
cd ..
sudo rm -rf magento
```
and rerun the whole one-line setup block from the `README.md`

**Comment by BBartt** [comment]
Hello, yes I was using WSL and got those errors. Thank you for comments but currently my WSL is crashing for some reason and I have 2 job interviews in a course of 7 days so I won't have really time to renstall stuff etc
Thank you for your commnets thought

**Comment by memory-hunter** [comment]
> Hello, yes I was using WSL and got those errors. Thank you for comments but currently my WSL is crashing for some reason and I have 2 job interviews in a course of 7 days so I won't have really time to renstall stuff etc
> Thank you for your commnets thought

Best of luck!

**Comment by markshust** [comment]
You can, but you'll need to modify the base url in Magento's config to use that port, and also update the ports in the `compose.yaml` file.

For example, to make it run on port 8080, you can update:
```
services:
  app:
    image: markoshust/magento-nginx:1.18-8
    ports:
      - "80:8000"
      - "443:8443"
...
```

to:
```
services:
  app:
    image: markoshust/magento-nginx:1.18-8
    ports:
      - "8080:8000"
      - "8443:8443"
...
```

Note that you may have issues with SSL though, and this practice isn't encouraged at the moment as it just leads to some headaches. Better to just stop the host machine from running anything on the main 80/443 ports.
