### ISSUE TITLE
Persistent storegae for elasticserach/opensearch

### ISSUE THREAD

**Issue by apresources** [markshust/docker-magento#977]
More of a suggestion than an issue.

We have seen startup performance improvements and less need to reindex etc when switching between projects, by persisting the opensearch/elasticsearch index in a volume

e.g. for opensearch in compose.yaml

```
  opensearch:
    image: markoshust/magento-opensearch:1.2-0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - opensearchdata:/usr/share/opensearch/data
    env_file: env/opensearch.env
    environment:
      - "discovery.type=single-node"
      ## Avoid test failures due to small disks
      ## More info at https://github.com/markshust/docker-magento/issues/488
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
```

and 

```
volumes:
  appdata:
  dbdata:
  opensearchdata:
  rabbitmqdata:
  sockdata:
  ssldata:
```
